### ISSUE TITLE
Cannot run the bot!

### ISSUE THREAD

**Issue by MajorTazer** [judge0/discord-bot#5]
I have done every step with an admin command prompt until the part where it comes to `pipenv run start <token>`.
I first did that code and it threw this error:
```
Traceback (most recent call last):
  File "F:\Anaconda\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Anaconda\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Python\JudgeBot\discord-bot\bot\__main__.py", line 23, in <module>
    token = sys.argv[1] if len(sys.argv) > 2 else os.environ["BOT_TOKEN"]
  File "C:\Users\taysi\.virtualenvs\discord-bot-ZAz7AEEA\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'BOT_TOKEN'
```
Then I went into my environment variables and added BOT_TOKEN with a value of my token. Then I tried `pipenv run start` but it threw the same error.

**Comment by MajorTazer** [comment]
Don't worry. I didn't restart after adding the variable so it was not in the PATH.
